splashScreenPath = "images\splashScreenImage.png"
logoPath = "favicon.ico"
userLogoPath = r"images\userLogo.png"
cardImage1Path = r"images\card_image-1.png"
cardImage2Path = r"images\card_image-2.png"
moneyIconPath = r"images\money_icon.png"